//
//  BuyAndSaleInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyAndSaleBusinessLogic
{
  func doSomething(request: BuyAndSale.Something.Request)
}

protocol BuyAndSaleDataStore
{
  //var name: String { get set }
}

class BuyAndSaleInteractor: BuyAndSaleBusinessLogic, BuyAndSaleDataStore
{
  var presenter: BuyAndSalePresentationLogic?
  var worker: BuyAndSaleWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BuyAndSale.Something.Request)
  {
    worker = BuyAndSaleWorker()
    worker?.doSomeWork()
    
    let response = BuyAndSale.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
