//
//  PortDetailModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 25/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PortDetail
{
  // MARK: Use cases
  
  enum PortNo{
    struct Request{
        
    }
    struct Response{
        var portno:Int
    }
    struct ViewModel{
        var portno:Int

    }
  }
    enum  DeletePort {
      struct Request {
        var delFlag: String
        var username: String
        var portNo: Int
        var channel: String
    
    
      }
      struct Response {
        var delete: DeleteModel?
        var error: Error?
      }
      struct ViewModel {
        var delete: DeleteModel?
          var error: Error?
      }
    }
}
