//
//  CalendarInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 16/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CalendarBusinessLogic {
  func doSomething(request: Calendar.Something.Request)
}

protocol CalendarDataStore {
  //var name: String { get set }
}

class CalendarInteractor: CalendarBusinessLogic, CalendarDataStore {
  var presenter: CalendarPresentationLogic?
  var worker: CalendarWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Calendar.Something.Request) {
    worker = CalendarWorker()
    worker?.doSomeWork()
    
    let response = Calendar.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
