//
//  AddSimulationPortRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 9/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddSimulationPortRoutingLogic
{
    func sendDatagoToRiskPreview(risk: Int?)
}

protocol AddSimulationPortDataPassing
{
  var dataStore: AddSimulationPortDataStore? { get }
}

class AddSimulationPortRouter: NSObject, AddSimulationPortRoutingLogic, AddSimulationPortDataPassing
{
  weak var viewController: AddSimulationPortViewController?
  var dataStore: AddSimulationPortDataStore?
  
  // MARK: Routing
    func sendDatagoToRiskPreview(risk: Int?) {
         let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RiskViewController") as! RiskViewController
         var destinationDS = destinationVC.router!.dataStore!
        destinationDS.risk = risk
        viewController?.present(destinationVC, animated: true)
        
    }
}
