//
//  MoreWorker.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON
class MoreWorker  {
    
    typealias Models = More
    typealias FecthAnalystReportDataCompletionHandler = (_ analystReportData: [AnalystReportModel]?,_ error: Error?) -> ()
  func doFetchAnalystReport(nameFunds:String, completionHandler: @escaping FecthAnalystReportDataCompletionHandler) {
        let router = Funds.analystReport
    Alamofire.request(router).responseJSON { response in
    //            print("Data",String(data: response.data!, encoding: .utf8)!)
                if response.error != nil {
                    completionHandler(nil, response.error)
                    return
                }
                if let data = response.value {
                    do {
                        let dataJSON = JSON(data)
                        let fundIPO = dataJSON["AnalystReport"]["IPO"]
                        let fundIPOData = try fundIPO.rawData(options: .fragmentsAllowed)
                        let analystReportData = try JSONDecoder().decode([AnalystReportModel].self, from: fundIPOData)
                        completionHandler(analystReportData, nil)
                    } catch let error {
                        completionHandler(nil, error)
                    }
                }
            }
        }
}
