//
//  MoreRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoreRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func goToFundAnalystReport(analystReportData: AnalystReportModel)
    func goToIPORollover()
}

protocol MoreDataPassing
{
  var dataStore: MoreDataStore? { get }
}

class MoreRouter: NSObject, MoreRoutingLogic, MoreDataPassing
{
  weak var viewController: MoreViewController?
  var dataStore: MoreDataStore?
  
  // MARK: Routing
  
    func goToFundAnalystReport(analystReportData: AnalystReportModel) {
        let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "FundAnslystReportViewController") as! FundAnslystReportViewController
            var destinationDS = destinationVC.router!.dataStore!
            destinationDS.analystReport = analystReportData
            viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    func goToIPORollover() {
        let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "IPORolloverViewController") as! IPORolloverViewController
             viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
}
