//
//  SSFInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SSFBusinessLogic
{
  func doSomething(request: SSF.Something.Request)
}

protocol SSFDataStore
{
  //var name: String { get set }
}

class SSFInteractor: SSFBusinessLogic, SSFDataStore
{
  var presenter: SSFPresentationLogic?
  var worker: SSFWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SSF.Something.Request)
  {
    worker = SSFWorker()
    worker?.doSomeWork()
    
    let response = SSF.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
