//
//  SSFPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SSFPresentationLogic
{
  func presentSomething(response: SSF.Something.Response)
}

class SSFPresenter: SSFPresentationLogic
{
  weak var viewController: SSFDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SSF.Something.Response)
  {
    let viewModel = SSF.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
