//
//  RiskPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RiskPresentationLogic {
  func presentSomething(response: Risk.Something.Response)
}

class RiskPresenter: RiskPresentationLogic {
  weak var viewController: RiskDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Risk.Something.Response) {
    let viewModel = Risk.Something.ViewModel(risk: response.risk)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
