//
//  RiskModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Risk {
  // MARK: Use cases
  
  enum Something {
    struct Request {
        
    }
    struct Response {
        var risk: Int?
    }
    struct ViewModel {
        var risk: Int?
    }
  }
}
