//
//  RiskInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RiskBusinessLogic {
  func doSomething(request: Risk.Something.Request)
}

protocol RiskDataStore {
  var risk: Int? { get set }
}

class RiskInteractor: RiskBusinessLogic, RiskDataStore {
  var presenter: RiskPresentationLogic?
  var worker: RiskWorker?
  var risk: Int?
  
  // MARK: Do something
  
  func doSomething(request: Risk.Something.Request) {
    worker = RiskWorker()
    worker?.doSomeWork()
    
    let response = Risk.Something.Response(risk: risk)
    presenter?.presentSomething(response: response)
  }
}
