//
//  RiskViewController.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RiskDisplayLogic: class {
  func displaySomething(viewModel: Risk.Something.ViewModel)
}

class RiskViewController: UIViewController, RiskDisplayLogic {
    @IBOutlet weak var navbar: UINavigationBar!
    @IBOutlet weak var imgRisk: UIImageView!
    @IBOutlet weak var lbfunds: UILabel!
    @IBOutlet weak var lbdetailfunds: UILabel!
    @IBOutlet weak var setslider: UISlider!
    @IBAction func slideraction(_ sender: UISlider) {
//        print("number", Int(sender.value))
        let number = Int(sender.value)
        self.sliderchange(number: number)
        
    }
    
    var risk: Int?
    var interactor: RiskBusinessLogic?
  var router: (NSObjectProtocol & RiskRoutingLogic & RiskDataPassing)?

    @IBAction func btnbacksecondsearch(_ sender: Any) {
        self.dismiss(animated: false, completion: nil)
    }
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = RiskInteractor()
    let presenter = RiskPresenter()
    let router = RiskRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    doSomething()
    self.navbar.barTintColor = UIColor.white;
    if  self.risk == 1 {
        self.setslider.value = 1
        self.imgRisk.image = #imageLiteral(resourceName: "111")
        self.lbfunds.text = "กองทุนรวมตลาดเงินที่ลงทุนเฉพาะในประเทศ"
        self.lbdetailfunds.text = "มีนโยบายลงทุนเฉพาะในประเทศไทย ดดยลงทุนในหรือมีไว้ซึ่งเงินฝาก หรือ ตราสารหนี้ หรือหลักทรัพท์ หรือทรัพท์สินอื่น หรือการหาดอกผลอื่นตามที่สำนักงานกำหนด ซึ่งมีกำหนดชำระคืนเมื่อทวงถามหรือจะครบกำหนดชำระคืน หรือมีอายุสัญญาไม่เกิน 1 ปี นับแต่วันที่ลงทุนในทรัพท์สินหรือเข้าทำสัญญานั้น และมี portfolio duration ในขณะใดขณะหนึ่ง ไม่เกิน 3 เดือน"
    } else if  self.risk == 2 {
        self.setslider.value = 2
        self.imgRisk.image = #imageLiteral(resourceName: "222")
        self.lbfunds.text = "กองทุนรวมตลาดเงิน"
        self.lbdetailfunds.text = "มีนโยบายลงทุนในต่างประเทศบางส่วน แต่ไม่เกินร้อยละ 50 ของ NAV โดยลงทุนในหรือมีไว้ซึ่งเงินฝาก หรือ ตราสารหนี้ หรือหลักทรัพย์ หรือทรัพย์สินอื่น หรือการหาดอกผลอื่นตามที่สำนักงานกำหนด ซึ่งมีกำหนดชำระคืนเมื่อทวงถามหรือจะครบกำหนดชำระคืน หรือมีอายุสัญญาไม่เกิน 1 ปี นับแต่วันที่ลงทุนในทรัพย์สินหรือเข้าทำสัญญานั้น รวมทั้งมี portfolio duration ในขณะหนึ่ง ไม่เกิน 3 เดือน"
    } else if  self.risk == 3 {
        self.setslider.value = 3
        self.imgRisk.image = #imageLiteral(resourceName: "333")
        self.lbfunds.text = "กองทุนรวมพันธบัตรรัฐบาล"
        self.lbdetailfunds.text = "มีนโยบายเน้นลงทุนในพันธบัตรรัฐบาลเฉลี่ยรอบปีบัญชีไม่น้อยกว่าร้อยละ 80 ของ NAV"
    }else if  self.risk == 4 {
        self.setslider.value = 4
        self.imgRisk.image = #imageLiteral(resourceName: "444")
        self.lbfunds.text = "กองทุนรวมตราสารแห่งหนี้"
        self.lbdetailfunds.text = "มีนโยบายลงทุนในตราสารหนี้ทั่วไป"
    }else if  self.risk == 5 {
        self.setslider.value = 5
        self.imgRisk.image = #imageLiteral(resourceName: "555")
        self.lbfunds.text = "กองทุนรวมผสม"
        self.lbdetailfunds.text = "มีนโยบายลงทุนได้ทั้งในตราสารทุนและตราสารหนี้"
    }else if  self.risk == 6 {
        self.setslider.value = 6
        self.imgRisk.image = #imageLiteral(resourceName: "666")
        self.lbfunds.text = "กองทุนรวมตราสารทุน"
        self.lbdetailfunds.text = "มีนโยบายลงทุนในตราสารทุนเป็นหลัก โดยเฉลี่ยรอบปีบัญชีไม่น้อยกว่าร้อยละ 65 ของ NAV"
    }else if  self.risk == 7 {
        self.setslider.value = 7
        self.imgRisk.image = #imageLiteral(resourceName: "777")
        self.lbfunds.text = "กองทุนรวมหมวดอุตาสหกรรม"
        self.lbdetailfunds.text = "มีนโยบายมุ่งลงทุนโดยเฉพาะเจาะจงในตราสารทุนเพียงบางหมวดอุตาสาหกรรม โดยเฉลี่ยรอบระยะเวลาบัญชีไม่น้อยกว่าร้อยละ 80 ของ NAV"
    } else  {
        self.setslider.value = 8
        self.imgRisk.image = #imageLiteral(resourceName: "888")
        self.lbfunds.text = "กองทุนรวมตลาดเงินที่ลงทุนเฉพาะในประเทศ"
        self.lbdetailfunds.text = "มีนโยบายลงทุนในทรัพย์สินที่เป็นทางเลิอกใหม่ในการลงทุนหรือมีโครงสร้างซับซ้อน เช้าใจยาก เช่น commodity/gold fund/oil fund/derivatives ที่ไม่ใช่เพื่อ hedging ซึ่งรวมถึงตราสารที่มีลักษณะของสัญญาซื้อขายล่วงหน้าแฝงที่ไไม่คุ้มครองเงินต้น"
    }
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    func sliderchange(number: Int) {
        if  number == 1 {
            self.imgRisk.image = #imageLiteral(resourceName: "111")
            self.lbfunds.text = "กองทุนรวมตลาดเงินที่ลงทุนเฉพาะในประเทศ"
            self.lbdetailfunds.text = "มีนโยบายลงทุนเฉพาะในประเทศไทย ดดยลงทุนในหรือมีไว้ซึ่งเงินฝาก หรือ ตราสารหนี้ หรือหลักทรัพท์ หรือทรัพท์สินอื่น หรือการหาดอกผลอื่นตามที่สำนักงานกำหนด ซึ่งมีกำหนดชำระคืนเมื่อทวงถามหรือจะครบกำหนดชำระคืน หรือมีอายุสัญญาไม่เกิน 1 ปี นับแต่วันที่ลงทุนในทรัพท์สินหรือเข้าทำสัญญานั้น และมี portfolio duration ในขณะใดขณะหนึ่ง ไม่เกิน 3 เดือน"
        } else if number == 2 {
            self.imgRisk.image = #imageLiteral(resourceName: "222")
            self.lbfunds.text = "กองทุนรวมตลาดเงิน"
            self.lbdetailfunds.text = "มีนโยบายลงทุนในต่างประเทศบางส่วน แต่ไม่เกินร้อยละ 50 ของ NAV โดยลงทุนในหรือมีไว้ซึ่งเงินฝาก หรือ ตราสารหนี้ หรือหลักทรัพย์ หรือทรัพย์สินอื่น หรือการหาดอกผลอื่นตามที่สำนักงานกำหนด ซึ่งมีกำหนดชำระคืนเมื่อทวงถามหรือจะครบกำหนดชำระคืน หรือมีอายุสัญญาไม่เกิน 1 ปี นับแต่วันที่ลงทุนในทรัพย์สินหรือเข้าทำสัญญานั้น รวมทั้งมี portfolio duration ในขณะหนึ่ง ไม่เกิน 3 เดือน"
        } else if  number == 3 {
            self.imgRisk.image = #imageLiteral(resourceName: "333")
            self.lbfunds.text = "กองทุนรวมพันธบัตรรัฐบาล"
            self.lbdetailfunds.text = "มีนโยบายเน้นลงทุนในพันธบัตรรัฐบาลเฉลี่ยรอบปีบัญชีไม่น้อยกว่าร้อยละ 80 ของ NAV"
        }else if  number == 4 {
            self.imgRisk.image = #imageLiteral(resourceName: "444")
            self.lbfunds.text = "กองทุนรวมตราสารแห่งหนี้"
            self.lbdetailfunds.text = "มีนโยบายลงทุนในตราสารหนี้ทั่วไป"
        }else if number == 5 {
            self.imgRisk.image = #imageLiteral(resourceName: "555")
            self.lbfunds.text = "กองทุนรวมผสม"
            self.lbdetailfunds.text = "มีนโยบายลงทุนได้ทั้งในตราสารทุนและตราสารหนี้"
        }else if  number == 6 {
            self.imgRisk.image = #imageLiteral(resourceName: "666")
            self.lbfunds.text = "กองทุนรวมตราสารทุน"
            self.lbdetailfunds.text = "มีนโยบายลงทุนในตราสารทุนเป็นหลัก โดยเฉลี่ยรอบปีบัญชีไม่น้อยกว่าร้อยละ 65 ของ NAV"
        }else if  number == 7 {
            self.imgRisk.image = #imageLiteral(resourceName: "777")
            self.lbfunds.text = "กองทุนรวมหมวดอุตาสหกรรม"
            self.lbdetailfunds.text = "มีนโยบายมุ่งลงทุนโดยเฉพาะเจาะจงในตราสารทุนเพียงบางหมวดอุตาสาหกรรม โดยเฉลี่ยรอบระยะเวลาบัญชีไม่น้อยกว่าร้อยละ 80 ของ NAV"
        } else  {
            self.imgRisk.image = #imageLiteral(resourceName: "888")
            self.lbfunds.text = "กองทุนที่มีการลงทุนในทรัพย์สินทางเลือก"
            self.lbdetailfunds.text = "มีนโยบายลงทุนในทรัพย์สินที่เป็นทางเลิอกใหม่ในการลงทุนหรือมีโครงสร้างซับซ้อน เช้าใจยาก เช่น commodity/gold fund/oil fund/derivatives ที่ไม่ใช่เพื่อ hedging ซึ่งรวมถึงตราสารที่มีลักษณะของสัญญาซื้อขายล่วงหน้าแฝงที่ไไม่คุ้มครองเงินต้น"
        }
    }
  func doSomething() {
    let request = Risk.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Risk.Something.ViewModel) {
    print("risk>>", viewModel.risk ?? 0)
    self.risk = viewModel.risk ?? 0
  }
}
