//
//  FundSaleViewController.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundSaleDisplayLogic: class
{
  func displaySomething(viewModel: FundSale.Something.ViewModel)
}

class FundSaleViewController: UIViewController, FundSaleDisplayLogic
{
    @IBAction func segmentControlPassed(_ sender: UISegmentedControl) {
       switch segmentControl.selectedSegmentIndex {
    
        case 0:
            self.textfield.placeholder = "0 บาท"
        case 1:
            self.textfield.placeholder = "0 หน่วย"
       case 2:
           self.textfield.placeholder = "2,250.2250 หน่วย"
        default:
            break
        }
    }
    @IBOutlet weak var segmentControl: UISegmentedControl!
    @IBOutlet weak var textfield: UITextField!
    @IBOutlet weak var navtitle: UINavigationItem!
    @IBOutlet weak var navBar: UINavigationBar!
    @IBAction func navBtnback(_ sender: Any) {
        self.dismiss(animated: false, completion: nil)
    }
    @IBAction func btnrisk(_ sender: Any) {
        router?.sendDatagoToRiskPreview(risk: 1)
    }
    @IBOutlet weak var setbtnactionCalendar: UIButton!
    @IBAction func btnactionCalendar(_ sender: Any) {
    }
    @IBOutlet weak var setbtnrisk: UIButton!
    @IBOutlet weak var lbenname: UILabel!
    @IBOutlet weak var lbthname: UILabel!
    @IBOutlet weak var setView: UIView!
  var interactor: FundSaleBusinessLogic?
  var router: (NSObjectProtocol & FundSaleRoutingLogic & FundSaleDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = FundSaleInteractor()
    let presenter = FundSalePresenter()
    let router = FundSaleRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
//    self.navtitle?.title = self.searchFunds?.assetCompany
    self.navBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor:UIColor.white]
    self.navBar.barTintColor = UIColor.systemBlue;
    self.setView.clipsToBounds = true
    self.setView.layer.cornerRadius = 15
//    self.setView.layer.shadowOpacity = 0.3
    self.setView.layer.shadowRadius = 10
    self.setView.layer.masksToBounds = false
    self.setbtnrisk.setImage(UIImage(named: "111"), for: .normal)
    let dataFormatter = DateFormatter()
    dataFormatter.dateFormat = "dd/MM/yyyy"
    let formattedDate = dataFormatter.string(from: Date())
    self.setbtnactionCalendar.setTitle(formattedDate, for: .normal)
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = FundSale.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: FundSale.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
