//
//  FundSaleInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundSaleBusinessLogic
{
  func doSomething(request: FundSale.Something.Request)
}

protocol FundSaleDataStore
{
  //var name: String { get set }
}

class FundSaleInteractor: FundSaleBusinessLogic, FundSaleDataStore
{
  var presenter: FundSalePresentationLogic?
  var worker: FundSaleWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FundSale.Something.Request)
  {
    worker = FundSaleWorker()
    worker?.doSomeWork()
    
    let response = FundSale.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
