//
//  FundSaleRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundSaleRoutingLogic
{
    func sendDatagoToRiskPreview(risk: Int?)
}

protocol FundSaleDataPassing
{
  var dataStore: FundSaleDataStore? { get }
}

class FundSaleRouter: NSObject, FundSaleRoutingLogic, FundSaleDataPassing
{
  weak var viewController: FundSaleViewController?
  var dataStore: FundSaleDataStore?
  
  // MARK: Routing
  
    func sendDatagoToRiskPreview(risk: Int?) {
         let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RiskViewController") as! RiskViewController
         var destinationDS = destinationVC.router!.dataStore!
        destinationDS.risk = risk
        viewController?.present(destinationVC, animated: true)
        
    }
}
