//
//  SimulationportPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 9/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SimulationportPresentationLogic
{
    func presentdoFecthGetOrderData(response: Simulationport.GetOrder.Response)
    func presentdoFecthGetOrderData2(response: Simulationport.GetOrder2.Response)
    func presentdoFecthGetOrderData3(response: Simulationport.GetOrder3.Response)
    func presentdoFecthGetOrderData4(response: Simulationport.GetOrder4.Response)
    func presentdoFecthGetOrderData5(response: Simulationport.GetOrder5.Response)
}

class SimulationportPresenter: SimulationportPresentationLogic
{
  weak var viewController: SimulationportDisplayLogic?
  
  // MARK: Do something
  
    func presentdoFecthGetOrderData(response: Simulationport.GetOrder.Response)
    {
      let getOrderData = response.getOrderDate
      let error = response.error
      let viewModel = Simulationport.GetOrder.ViewModel(getOrderDate: getOrderData, error: error)
      viewController?.displayFecthGetOrderData(viewModel: viewModel)
    }
      func presentdoFecthGetOrderData2(response: Simulationport.GetOrder2.Response) {
          let getOrderData2 = response.getOrderDate2
          let error = response.error
          let viewModel = Simulationport.GetOrder2.ViewModel(getOrderDate2: getOrderData2, error: error)
          viewController?.displayFecthGetOrderData2(viewModel: viewModel)
      }
      func presentdoFecthGetOrderData3(response: Simulationport.GetOrder3.Response) {
          let getOrderData3 = response.getOrderDate3
          let error = response.error
          let viewModel = Simulationport.GetOrder3.ViewModel(getOrderDate3: getOrderData3, error: error)
          viewController?.displayFecthGetOrderData3(viewModel: viewModel)
      }
      func presentdoFecthGetOrderData4(response: Simulationport.GetOrder4.Response) {
          let getOrderData4 = response.getOrderDate4
          let error = response.error
          let viewModel = Simulationport.GetOrder4.ViewModel(getOrderDate4: getOrderData4, error: error)
          viewController?.displayFecthGetOrderData4(viewModel: viewModel)
      }
      func presentdoFecthGetOrderData5(response: Simulationport.GetOrder5.Response) {
          let getOrderData5 = response.getOrderDate5
          let error = response.error
          let viewModel = Simulationport.GetOrder5.ViewModel(getOrderDate5: getOrderData5, error: error)
          viewController?.displayFecthGetOrderData5(viewModel: viewModel)
      }
}
