//
//  SimulationportRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 9/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SimulationportRoutingLogic
{
    func goToSearchFundsPreview(mainpage: String)
    func goToPortDetail(portNo: Int )
}

protocol SimulationportDataPassing
{
  var dataStore: SimulationportDataStore? { get }
}

class SimulationportRouter: NSObject, SimulationportRoutingLogic, SimulationportDataPassing
{
  weak var viewController: SimulationportViewController?
  var dataStore: SimulationportDataStore?
  
  // MARK: Routing
  
    func goToSearchFundsPreview(mainpage: String) {
         let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SearchFundsViewController") as! SearchFundsViewController
        var destinationDS = destinationVC.router!.dataStore!
        destinationDS.mainpage = mainpage
        viewController?.present(destinationVC, animated: true)
    }
    func goToPortDetail(portNo: Int ) {
        let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "PortDetailViewController") as! PortDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        destinationDS.portNo = portNo
        viewController?.present(destinationVC, animated: true, completion: nil)
   }
}
