//
//  SecondSearchPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondSearchPresentationLogic {
  func presentSomething(response: SecondSearch.Something.Response)
}

class SecondSearchPresenter: SecondSearchPresentationLogic {
  weak var viewController: SecondSearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SecondSearch.Something.Response) {
    let viewModel = SecondSearch.Something.ViewModel(searchfunds: response.searchfunds)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
