//
//  SecondSearchRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondSearchRoutingLogic {
    func sendDatagoToRiskPreview(risk: Int?)
    func sendPicegoToBuyPreview()
}

protocol SecondSearchDataPassing {
  var dataStore: SecondSearchDataStore? { get }
}

class SecondSearchRouter: NSObject, SecondSearchRoutingLogic, SecondSearchDataPassing {
  weak var viewController: SecondSearchViewController?
  var dataStore: SecondSearchDataStore?
  
  // MARK: Routing
    func sendDatagoToRiskPreview(risk: Int?) {
         let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RiskViewController") as! RiskViewController
         var destinationDS = destinationVC.router!.dataStore!
        destinationDS.risk = risk
        viewController?.present(destinationVC, animated: true)
        
    }
    func sendPicegoToBuyPreview() {
//        let destinationtabbarVC = UITapbar.performSegue(withIdentifier: "tabBar", sender: self
       
        viewController?.view.window?.rootViewController?.dismiss(animated: true, completion: nil)
        
    }
}
