//
//  SearchFundsPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchFundsPresentationLogic {
  func presentSearchFunds(response: SearchFunds.FetchSearchFundsData.Response)
    func presentMainPageName(response: SearchFunds.FetchMainPageName.Response)
}

class SearchFundsPresenter: SearchFundsPresentationLogic {
  weak var viewController: SearchFundsDisplayLogic?
  
  // MARK: Do something
    func presentSearchFunds(response: SearchFunds.FetchSearchFundsData.Response) {
        let searchFundsdata = response.searchfunds
        let error = response.error
    //        print("fundsIPOData", fundsIPOData)
        let viewModel = SearchFunds.FetchSearchFundsData.ViewModel(searchfunds: searchFundsdata, error: error)
        viewController?.displaySearchFunds(viewModel: viewModel)
  }
    func presentMainPageName(response: SearchFunds.FetchMainPageName.Response) {
        let viewModel = SearchFunds.FetchMainPageName.ViewModel(mainpage:  response.mainpage)
        viewController?.displayMainPageName(viewModel: viewModel)
    }
}
