//
//  SearchFundsModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchFunds {
  // MARK: Use cases
  
    enum FetchSearchFundsData {
      struct Request {
         
      }
      struct Response {
          var searchfunds: [SearchFundsModel]?
          var error: Error?
      }
      struct ViewModel {
          var searchfunds: [SearchFundsModel]?
          var error: Error?
      }
    }
    enum FetchMainPageName {
      struct Request {
         
      }
      struct Response {
        var mainpage: String?
         
      }
      struct ViewModel {
        var mainpage: String?
      }
    }
}
