//
//  SearchFundsWorker.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON
class SearchFundsWorker
{
    typealias Models = SearchFunds
    typealias FecthSearchFundsDataCompletionHandler = (_ searchFundsData: [SearchFundsModel]?,_ error: Error?) -> ()
    func fetchFundsIPOData(completionHandler: @escaping FecthSearchFundsDataCompletionHandler) {
        let router = Funds.fundsList
        Alamofire.request(router).responseJSON { response in
            
            if response.error != nil {
                completionHandler(nil, response.error)
                return
            }
            
            if let data = response.data {
                do {
                    let searchFundsModelData = try JSONDecoder().decode([SearchFundsModel].self, from: data)
                    completionHandler(searchFundsModelData, nil)
                    
                } catch let error {
                    completionHandler(nil, error)
               
                }
            }
        }
    }
}
