//
//  SearchFundsRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchFundsRoutingLogic {
    func sendDatagoToSecondSearchPreview(fundsList: ReealmFundsListMobile)
    func sendDatagoToAddPortPreview(fundsList: ReealmFundsListMobile)
}

protocol SearchFundsDataPassing
{
  var dataStore: SearchFundsDataStore? { get }
}

class SearchFundsRouter: NSObject, SearchFundsRoutingLogic, SearchFundsDataPassing
{
  weak var viewController: SearchFundsViewController?
  var dataStore: SearchFundsDataStore?
  
  // MARK: Routing
  
    func sendDatagoToSecondSearchPreview(fundsList: ReealmFundsListMobile) {
         let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SecondSearchViewController") as! SecondSearchViewController
         var destinationDS = destinationVC.router!.dataStore!
        destinationDS.searchfunds = fundsList
        viewController?.present(destinationVC, animated: false)
        
    }
    
      func sendDatagoToAddPortPreview(fundsList: ReealmFundsListMobile) {
           let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "AddSimulationPortViewController") as! AddSimulationPortViewController
           var destinationDS = destinationVC.router!.dataStore!
          destinationDS.searchfunds = fundsList
          viewController?.present(destinationVC, animated: false)
          
      }
}
