//
//  SearchFundsInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import UIKit

protocol SearchFundsBusinessLogic {
    func doFetchSearchFunds(request: SearchFunds.FetchSearchFundsData.Request)
    func doFetchMainPageName(request: SearchFunds.FetchMainPageName.Request)
}

protocol SearchFundsDataStore {
    var searchFundsData: [SearchFundsModel]? { get set }
    var mainpage: String {get set}
    
}

class SearchFundsInteractor: SearchFundsBusinessLogic, SearchFundsDataStore {
   
    var presenter: SearchFundsPresentationLogic?
    var worker: SearchFundsWorker?
    var searchFundsData: [SearchFundsModel]?
    var mainpage: String = ""
  // MARK: Do something
    func doFetchSearchFunds(request: SearchFunds.FetchSearchFundsData.Request) {
    worker = SearchFundsWorker()
    worker?.fetchFundsIPOData { (searchFundsData , error ) in
            if error != nil {
                let response = SearchFunds.FetchSearchFundsData.Response(searchfunds: nil, error: error)
                self.presenter?.presentSearchFunds(response: response)
            }
            
            let response = SearchFunds.FetchSearchFundsData.Response(searchfunds: searchFundsData, error: nil)
          
            self.presenter?.presentSearchFunds(response: response)
        }
    }
    func doFetchMainPageName(request: SearchFunds.FetchMainPageName.Request){
        let response = SearchFunds.FetchMainPageName.Response(mainpage: mainpage)
//        print("mainpage", mainpage)
        self.presenter?.presentMainPageName(response: response)
    }
}
