//
//  HomepagePresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomepagePresentationLogic
{
  func presentSomething(response: Homepage.Something.Response)
}

class HomepagePresenter: HomepagePresentationLogic
{
  weak var viewController: HomepageDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Homepage.Something.Response)
  {
    let viewModel = Homepage.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
