//
//  HomepageInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomepageBusinessLogic
{
  func doSomething(request: Homepage.Something.Request)
}

protocol HomepageDataStore
{
  //var name: String { get set }
}

class HomepageInteractor: HomepageBusinessLogic, HomepageDataStore
{
  var presenter: HomepagePresentationLogic?
  var worker: HomepageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Homepage.Something.Request)
  {
    worker = HomepageWorker()
    worker?.doSomeWork()
    
    let response = Homepage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
