//
//  IPORolloverPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IPORolloverPresentationLogic
{
  func presentFetchFundsIPO(response: IPORollovers.FetchFromRemoteDataStore.Response)
}

class IPORolloverPresenter: IPORolloverPresentationLogic
{
  weak var viewController: IPORolloverDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchFundsIPO(response: IPORollovers.FetchFromRemoteDataStore.Response)
  {
    let fundsIPOData = response.fundsIPO
    let error = response.error
//        print("fundsIPOData", fundsIPOData)
    let viewModel = IPORollovers.FetchFromRemoteDataStore.ViewModel(fundsIPO: fundsIPOData, error: error)
    viewController?.displayfundIPO(viewModel: viewModel)
  }
}
