//
//  IPORolloverRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IPORolloverRoutingLogic
{
    func goToFundIPO(fundsIPORollover: FundIPORolloverDataModels)
}

protocol IPORolloverDataPassing
{
  var dataStore: IPORolloverDataStore? { get }
}

class IPORolloverRouter: NSObject, IPORolloverRoutingLogic, IPORolloverDataPassing
{
  weak var viewController: IPORolloverViewController?
  var dataStore: IPORolloverDataStore?
  
    func goToFundIPO(fundsIPORollover: FundIPORolloverDataModels) {
        let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "FundsIPOViewController") as! FundsIPOViewController
        var destinationDS = destinationVC.router!.dataStore!
        destinationDS.fundsIPO = fundsIPORollover
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
   }
       }

