//
//  SaveDividendPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 16/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SaveDividendPresentationLogic
{
  func presentSomething(response: SaveDividend.Something.Response)
}

class SaveDividendPresenter: SaveDividendPresentationLogic
{
  weak var viewController: SaveDividendDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SaveDividend.Something.Response)
  {
    let viewModel = SaveDividend.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
