//
//  SaveDividendInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 16/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SaveDividendBusinessLogic
{
  func doSomething(request: SaveDividend.Something.Request)
}

protocol SaveDividendDataStore
{
  //var name: String { get set }
}

class SaveDividendInteractor: SaveDividendBusinessLogic, SaveDividendDataStore
{
  var presenter: SaveDividendPresentationLogic?
  var worker: SaveDividendWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SaveDividend.Something.Request)
  {
    worker = SaveDividendWorker()
    worker?.doSomeWork()
    
    let response = SaveDividend.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
