//
//  FIFViewController.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FIFDisplayLogic: class
{
  func displaySomething(viewModel: FIF.Something.ViewModel)
}

class FIFViewController: UIViewController, FIFDisplayLogic
{
    
    var name = [["Name": "KF-HEUROPE"],["Name": "KFSMART"],["Name": "M-ATECH"],["Name": "MCHINAGA"],["Name": "ONE-UGG-RA"]]
    var number = [["Number": "18.2334"],["Number": "10.7308"],["Number": "16.8849"],["Number": "14.3914"],["Number": "37.4813"]]
    var double = [["Double": "+6.37%"],["Double": "+0.08%"],["Double": "+10.01%"],["Double": "+14.98%"],["Double": "+6.70%"]]
    var funds = [["Fund": "กองทุนเปิดกรุงศรียุโรปอิควิตี้เฮดจ์"],["Fund": "กองทุนเปิดกรุงศรีสมาร์ทตราสารหนี้"],["Fund": "กองทุนเปิดเอ็มเอฟซี เอเชีย เทคโนโลยี"],["Fund": "กองทุนเปิดเอ็มเอฟซี ไชน่า อิควิตี้ ชนิดผู้ลงทุนทั่วไปที่ไม่รับเงินปันผล"],["Fund": "กองทุนเปิด วรรณ อัลติเมท โกลบอล โกรว์ธ (ชนิดไม่จ่ายเงินปันผล)"]],
      datesss =  [["Dates": "11/01/2564"],["Dates": "12/01/2564"],["Dates": "08/01/2564"],["Dates": "11/01/2564"],["Dates": "11/01/2564"]]
    var months =  [["Month": "1เดือน"],["Month": "1เดือน"],["Month": "1เดือน"],["Month": "1เดือน"],["Month": "1เดือน"]]

  var interactor: FIFBusinessLogic?
  var router: (NSObjectProtocol & FIFRoutingLogic & FIFDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = FIFInteractor()
    let presenter = FIFPresenter()
    let router = FIFRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = FIF.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: FIF.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
extension FIFViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return 5
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "FIFViewCell") as! FIFViewCell
//        let cell = tableView.dequeueReusableCell(withIdentifier: "SSFViewCell") as! SSFViewCell
        cell.data = name[indexPath.row]
        cell.dates = datesss[indexPath.row]
        cell.doubles = double[indexPath.row]
        cell.funds = funds[indexPath.row]
        cell.numbers = number[indexPath.row]
        cell.months = months[indexPath.row]
        return cell
    }
    
    
}
