//
//  BuyInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyBusinessLogic {
    func doMoney(request: Buy.FetchMoneyData.Request)
}

protocol BuyDataStore {
  
    var money: String? { get set }
}

class BuyInteractor: BuyBusinessLogic, BuyDataStore {
    var money: String?
  var presenter: BuyPresentationLogic?
  var worker: BuyWorker?
   
  //var name: String = ""
  
  // MARK: Do something
    func doMoney(request: Buy.FetchMoneyData.Request) {
        let response = Buy.FetchMoneyData.Response(money: money)
        print("Data", response.money ?? "")
        presenter?.presentdomoney(response: response)
    }
}
