//
//  BuyModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Buy {
  // MARK: Use cases
  

    enum FetchMoneyData {
      struct Request {
         
      }
      struct Response {
        var money: String?
      }
      struct ViewModel {
        var money: String?
      }
    }

}
