//
//  FundsIPOInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundsIPOBusinessLogic
{
    func setupFetchFromLocalDataStore(request: FundsIPO.FetchFromLocalDataStore.Request)}

protocol FundsIPODataStore
{
    var fundsIPO: FundIPORolloverDataModels? { get set }

}

class FundsIPOInteractor: FundsIPOBusinessLogic, FundsIPODataStore
{

    
    var fundsIPO: FundIPORolloverDataModels?
    
  var presenter: FundsIPOPresentationLogic?
  var worker: FundsIPOWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func setupFetchFromLocalDataStore(request: FundsIPO.FetchFromLocalDataStore.Request)
    {
      worker = FundsIPOWorker()
      worker?.doSomeWork()
      
      let response = FundsIPO.FetchFromLocalDataStore.Response(iPOData: fundsIPO)
      presenter?.presentSomething(response: response)
    }
}
