//
//  FundsIPOPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundsIPOPresentationLogic
{
    func presentSomething(response: FundsIPO.FetchFromLocalDataStore.Response)
}

class FundsIPOPresenter: FundsIPOPresentationLogic
{
  weak var viewController: FundsIPODisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: FundsIPO.FetchFromLocalDataStore.Response)
    {
      let viewModel = FundsIPO.FetchFromLocalDataStore.ViewModel(iPOData: response.iPOData)
      viewController?.displayFetchFromLocalDataStore(viewModel: viewModel)
    }
}
