//
//  PaymentPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 18/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentPresentationLogic
{
  func presentSomething(response: Payment.Something.Response)
}

class PaymentPresenter: PaymentPresentationLogic
{
  weak var viewController: PaymentDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Payment.Something.Response)
  {
    let viewModel = Payment.Something.ViewModel(picefunds: response.picefunds,enName: response.enName, thName: response.thName, risk: response.risk, date: response.date)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
