//
//  PaymentModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 18/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Payment
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        
    }
    struct Response
    {
        var picefunds: String?
        var enName: String?
        var thName: String?
        var risk: String?
        var date: String?
    }
    struct ViewModel
    {
        var picefunds: String?
        var enName: String?
        var thName: String?
        var risk: String?
        var date: String?
    }
  }
}
