//
//  DeleteMenuPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeleteMenuPresentationLogic
{
  func presentfetchHistory(response: DeleteMenu.FetchHistoryData.Response)
    func presentDeleteOrder(response: DeleteMenu.DeleteOrderNo.Response)
    func presentDeleteFcode(response: DeleteMenu.DeleteFcode.Response)
    
}

class DeleteMenuPresenter: DeleteMenuPresentationLogic
{
  weak var viewController: DeleteMenuDisplayLogic?
  
  // MARK: Do something
  
  func presentfetchHistory(response: DeleteMenu.FetchHistoryData.Response)
  {
    let viewModel = DeleteMenu.FetchHistoryData.ViewModel(getHistory: response.getHistory, error: response.error)
    viewController?.displayfetchHistory(viewModel: viewModel)
  }
    func presentDeleteOrder(response: DeleteMenu.DeleteOrderNo.Response) {
        let viewModel = DeleteMenu.DeleteOrderNo.ViewModel(delorder: response.delorder, error: response.error)
        viewController?.displaydeleteorder(viewModel: viewModel)
}
    func presentDeleteFcode(response: DeleteMenu.DeleteFcode.Response){
        let viewModel = DeleteMenu.DeleteFcode.ViewModel(delorder: response.delorder, error: response.error)
        viewController?.displaydeletefcode(viewModel: viewModel)
    }
}
