//
//  DeleteMenuModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DeleteMenu
{
  // MARK: Use cases
  
  enum FetchHistoryData
  {
    struct Request
    {
        var username: String
        var portno: Int
        var fcode: String
    }
    struct Response
    {
        var getHistory: GetHistoryModel?
        var error: Error?
    }
    struct ViewModel
    {
        var getHistory: GetHistoryModel?
        var error: Error?
    }
  }
    
    enum DeleteOrderNo {
      struct Request
      {
        var delflag: String
        var username: String
        var portno: Int
        var channel: String
        var ordno: Int
      }
      struct Response
      {
        var delorder: DeleteModel?
          var error: Error?
      }
      struct ViewModel
      {
        var delorder: DeleteModel?
          var error: Error?
      }
    }
    
    enum DeleteFcode {
      struct Request
      {
        var delflag: String
        var username: String
        var portno: Int
        var channel: String
        var fcode: String
      }
      struct Response
      {
        var delorder: DeleteModel?
          var error: Error?
      }
      struct ViewModel
      {
        var delorder: DeleteModel?
          var error: Error?
      }
    }
}
