//
//  ChangeInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeBusinessLogic
{
  func doSomething(request: Change.Something.Request)
}

protocol ChangeDataStore
{
  //var name: String { get set }
}

class ChangeInteractor: ChangeBusinessLogic, ChangeDataStore
{
  var presenter: ChangePresentationLogic?
  var worker: ChangeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Change.Something.Request)
  {
    worker = ChangeWorker()
    worker?.doSomeWork()
    
    let response = Change.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
