//
//  ChangeViewController.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeDisplayLogic: class
{
  func displaySomething(viewModel: Change.Something.ViewModel)
}

class ChangeViewController: UIViewController, ChangeDisplayLogic
{
    @IBOutlet weak var viewFunds: UIView!
    @IBOutlet weak var viewbtn: UIView!
    var interactor: ChangeBusinessLogic?
  var router: (NSObjectProtocol & ChangeRoutingLogic & ChangeDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ChangeInteractor()
    let presenter = ChangePresenter()
    let router = ChangeRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
    self.viewFunds.clipsToBounds = true
    self.viewFunds.layer.cornerRadius = 5
    self.viewFunds.layer.shadowColor = UIColor.systemGray.cgColor
    self.viewFunds.layer.shadowOpacity = 0.5
    self.viewFunds.layer.shadowRadius = 6
    self.viewFunds.layer.masksToBounds = false
    
    self.viewbtn.clipsToBounds = true
    self.viewbtn.layer.cornerRadius = 15
    self.viewbtn.layer.shadowColor = UIColor.systemGray.cgColor
    self.viewbtn.layer.shadowOpacity = 0.5
    self.viewbtn.layer.shadowRadius = 10
    self.viewbtn.layer.masksToBounds = false
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Change.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Change.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
