//
//  RMFInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RMFBusinessLogic
{
  func doSomething(request: RMF.Something.Request)
}

protocol RMFDataStore
{
  //var name: String { get set }
}

class RMFInteractor: RMFBusinessLogic, RMFDataStore
{
  var presenter: RMFPresentationLogic?
  var worker: RMFWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RMF.Something.Request)
  {
    worker = RMFWorker()
    worker?.doSomeWork()
    
    let response = RMF.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
