//
//  SalePresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 8/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SalePresentationLogic
{
  func presentSomething(response: Sale.Something.Response)
}

class SalePresenter: SalePresentationLogic
{
  weak var viewController: SaleDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Sale.Something.Response)
  {
    let viewModel = Sale.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
