//
//  FundAnslystReportPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundAnslystReportPresentationLogic
{
    func presentSomething(response: FundAnslystReport.Something.Response)
    func presentWeekly(response: FundAnslystReport.WeeklyData.Response)
    func presentMonthly(response: FundAnslystReport.MonthlyData.Response)
    func presentAnalystTalks(response: FundAnslystReport.AnalystTalk.Response)
}

class FundAnslystReportPresenter: FundAnslystReportPresentationLogic
{
  weak var viewController: FundAnslystReportDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FundAnslystReport.Something.Response)
  {
    let viewModel = FundAnslystReport.Something.ViewModel(analystReportData: response.analystReportData)
    viewController?.displaySomething(viewModel: viewModel)
  }
    func presentWeekly(response: FundAnslystReport.WeeklyData.Response) {
        let viewModel = FundAnslystReport.WeeklyData.ViewModel(analystReportWeeklyData: response.analystReportWeeklyData)
        viewController?.displayWeekly(viewModel: viewModel)
    }
    func presentMonthly(response: FundAnslystReport.MonthlyData.Response){
        let viewModel = FundAnslystReport.MonthlyData.ViewModel(analystReportMonthlyData: response.analystReportMonthlyData)
        viewController?.displayMonthly(viewModel: viewModel)
    }
    func presentAnalystTalks(response: FundAnslystReport.AnalystTalk.Response) {
        let viewModel = FundAnslystReport.AnalystTalk.ViewModel(analystTalkData: response.analystTalkData , error: response.error)
        viewController?.displayAnalystTalks(viewModel: viewModel)
    }
}
