# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'QuizFundsPhillip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizFundsPhillip
  pod 'Alamofire'	
  pod 'SwiftyJSON'
  pod 'LanguageManager-iOS'
  pod 'SDWebImage'
  pod 'Parchment'
  pod 'FSPagerView'
  pod 'CircleImageView'
  pod 'IQKeyboardManagerSwift'
  pod 'RealmSwift'
  pod 'FSCalendar'
  pod "CenteredCollectionView"
  pod 'UIColor_Hex_Swift'
end
